---
apiVersion: v1 
kind: Service
metadata:
  name: vote
  labels:
    app: vote
spec:
  selector:
    app: vote
  type: NodePort
  ports:
    - name: vote-service
      port: 5000
      targetPort: 80
      nodePort: 30090
